version: "3"
services:

  db:
    image: mysql:latest
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  wordpress:
    image: wordpress:latest
    command: bash -c "apt-get update && apt-get install -y ssl-cert && a2enmod ssl headers && apache2-foreground"
    #restart: always
    volumes:
      - ./etc/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./etc/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./var/logs:/var/log/apache2
      - ./var/www/html:/var/www/html
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    #restart: always
    depends_on:
      - db
    ports:
      - 8888:80

  mailcatcher:
    #restart: always
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
