version: "3"
services:

  db:
    image: mysql:latest
    container_name: db
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    #restart: always
    volumes:
      - ./var/www/html:/var/www/html
      - ./etc/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    #restart: always
    depends_on:
      - db
    ports:
      - 8888:80
